name: CI

on:
  push:
    branches:
      - main
      - feature/*
      - bugfix/*
  pull_request:
    branches: [main]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t neo .

      - name: Run Black (clean_vep_ann_vcf.py)
        run: |
          docker run --rm -v ${{ github.workspace }}:/app neo \
            sh -c "black --check /app/scripts/epitope_prediction/*.py"

      - name: Run Black (vcf_to_csv.py)
        run: |
          docker run --rm -v ${{ github.workspace }}:/app neo \
            sh -c "black --check /app/scripts/vcf_expression_annotator/*.py"

      - name: Run pytest
        run: |
          docker run --rm -v ${{ github.workspace }}:/app neo \
            pytest '/app/**/test*.py'
