name: CI

on:
  push:
    branches:
      - main
      - feature/*
      - bugfix/*
  pull_request:
    branches: [main]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pytest cyvcf2

      - name: Run Black (epitope_prediction)
        run: black --check scripts/epitope_prediction/*.py

      - name: Run Black (vcf_expression_annotator)
        run: black --check scripts/vcf_expression_annotator/*.py

      - name: Run pytest
        run: pytest '**/test*.py'

      - name: Build Docker image
        run: docker build -t neo .
